// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQz7Jfhuk1By9gFWUXAlBRQmA9chPobmY',
    appId: '1:326022795774:web:aba01a4b266f886f6cf0af',
    messagingSenderId: '326022795774',
    projectId: 'soreconnect-76e06',
    authDomain: 'soreconnect-76e06.firebaseapp.com',
    storageBucket: 'soreconnect-76e06.firebasestorage.app',
    measurementId: 'G-DKNBKSBFXB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrIih-MtLYSXv-oVnN7ysgKR6w2HCsOGc',
    appId: '1:326022795774:android:360a6a1f953dad386cf0af',
    messagingSenderId: '326022795774',
    projectId: 'soreconnect-76e06',
    storageBucket: 'soreconnect-76e06.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKT4sD5okAvlZUeGwIK_-3CwdYJY_PeWQ',
    appId: '1:326022795774:ios:c8f0d589321712ca6cf0af',
    messagingSenderId: '326022795774',
    projectId: 'soreconnect-76e06',
    storageBucket: 'soreconnect-76e06.firebasestorage.app',
    iosBundleId: 'com.example.soreconnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKT4sD5okAvlZUeGwIK_-3CwdYJY_PeWQ',
    appId: '1:326022795774:ios:c8f0d589321712ca6cf0af',
    messagingSenderId: '326022795774',
    projectId: 'soreconnect-76e06',
    storageBucket: 'soreconnect-76e06.firebasestorage.app',
    iosBundleId: 'com.example.soreconnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQz7Jfhuk1By9gFWUXAlBRQmA9chPobmY',
    appId: '1:326022795774:web:e533123c158e86356cf0af',
    messagingSenderId: '326022795774',
    projectId: 'soreconnect-76e06',
    authDomain: 'soreconnect-76e06.firebaseapp.com',
    storageBucket: 'soreconnect-76e06.firebasestorage.app',
    measurementId: 'G-ZJQZ419E7T',
  );

}